import './animation/headerFixed.js';
import './animation/hero.js';
import './animation/textAnimation.js';
import './animation/container.js';
import './animation/icon.js';
import './animation/loading.js';
import './animation/scrollTo.js';
import './animation/darkMode.js';
import './animation/scrollTop.js';